# Generated by Django 3.0.8 on 2020-07-22 19:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(default='2 Bach Dang', max_length=50)),
                ('city', models.CharField(default='sutrix', max_length=60)),
                ('state_province', models.CharField(default='HCM', max_length=30)),
                ('country', models.CharField(default='Viet Nam', max_length=50)),
                ('website', models.URLField(default='abc.com')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publication_date', models.DateField(default=datetime.date.today)),
                ('authors', models.ManyToManyField(related_name='newbook', to='books.Author')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.Publisher')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
